/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MyPawsRouteImport } from './routes/my-paws'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings/$bookingId'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as ClientsNewRouteImport } from './routes/clients/new'
import { Route as InvoicesNewRouteImport } from './routes/invoices/new'
import { Route as PawreportTokenRouteImport } from './routes/pawreport/$token'
import { Route as PetsIndexRouteImport } from './routes/pets/index'
import { Route as PetsPetIdRouteImport } from './routes/pets/$petId'
import { Route as PetsNewRouteImport } from './routes/pets/new'
import { Route as VisitsIndexRouteImport } from './routes/visits/index'
import { Route as VisitsVisitIdRouteImport } from './routes/visits/$visitId'
import { Route as WalksWalkIdRouteImport } from './routes/walks/$walkId'
import { Route as WalksWalkIdReportRouteImport } from './routes/walks/$walkId.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPawsRoute = MyPawsRouteImport.update({
  id: '/my-paws',
  path: '/my-paws',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const PawreportTokenRoute = PawreportTokenRouteImport.update({
  id: '/pawreport/$token',
  path: '/pawreport/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsIndexRoute = PetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdRoute = PetsPetIdRouteImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsNewRoute = PetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsIndexRoute = VisitsIndexRouteImport.update({
  id: '/visits/',
  path: '/visits/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsVisitIdRoute = VisitsVisitIdRouteImport.update({
  id: '/visits/$visitId',
  path: '/visits/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)
const WalksWalkIdRoute = WalksWalkIdRouteImport.update({
  id: '/walks/$walkId',
  path: '/walks/$walkId',
  getParentRoute: () => rootRouteImport,
} as any)
const WalksWalkIdReportRoute = WalksWalkIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => WalksWalkIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/gallery': typeof GalleryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/my-paws': typeof MyPawsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/pawreport/$token': typeof PawreportTokenRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/new': typeof PetsNewRoute
  '/visits/$visitId': typeof VisitsVisitIdRoute
  '/walks/$walkId': typeof WalksWalkIdRouteWithChildren
  '/clients/': typeof ClientsIndexRoute
  '/pets/': typeof PetsIndexRoute
  '/visits/': typeof VisitsIndexRoute
  '/walks/$walkId/report': typeof WalksWalkIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/gallery': typeof GalleryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/my-paws': typeof MyPawsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/pawreport/$token': typeof PawreportTokenRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/new': typeof PetsNewRoute
  '/visits/$visitId': typeof VisitsVisitIdRoute
  '/walks/$walkId': typeof WalksWalkIdRouteWithChildren
  '/clients': typeof ClientsIndexRoute
  '/pets': typeof PetsIndexRoute
  '/visits': typeof VisitsIndexRoute
  '/walks/$walkId/report': typeof WalksWalkIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/gallery': typeof GalleryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/my-paws': typeof MyPawsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/pawreport/$token': typeof PawreportTokenRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/new': typeof PetsNewRoute
  '/visits/$visitId': typeof VisitsVisitIdRoute
  '/walks/$walkId': typeof WalksWalkIdRouteWithChildren
  '/clients/': typeof ClientsIndexRoute
  '/pets/': typeof PetsIndexRoute
  '/visits/': typeof VisitsIndexRoute
  '/walks/$walkId/report': typeof WalksWalkIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/gallery'
    | '/invoices'
    | '/login'
    | '/messages'
    | '/more'
    | '/my-paws'
    | '/reports'
    | '/settings'
    | '/bookings/$bookingId'
    | '/clients/$clientId'
    | '/clients/new'
    | '/invoices/new'
    | '/pawreport/$token'
    | '/pets/$petId'
    | '/pets/new'
    | '/visits/$visitId'
    | '/walks/$walkId'
    | '/clients/'
    | '/pets/'
    | '/visits/'
    | '/walks/$walkId/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/gallery'
    | '/invoices'
    | '/login'
    | '/messages'
    | '/more'
    | '/my-paws'
    | '/reports'
    | '/settings'
    | '/bookings/$bookingId'
    | '/clients/$clientId'
    | '/clients/new'
    | '/invoices/new'
    | '/pawreport/$token'
    | '/pets/$petId'
    | '/pets/new'
    | '/visits/$visitId'
    | '/walks/$walkId'
    | '/clients'
    | '/pets'
    | '/visits'
    | '/walks/$walkId/report'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/gallery'
    | '/invoices'
    | '/login'
    | '/messages'
    | '/more'
    | '/my-paws'
    | '/reports'
    | '/settings'
    | '/bookings/$bookingId'
    | '/clients/$clientId'
    | '/clients/new'
    | '/invoices/new'
    | '/pawreport/$token'
    | '/pets/$petId'
    | '/pets/new'
    | '/visits/$visitId'
    | '/walks/$walkId'
    | '/clients/'
    | '/pets/'
    | '/visits/'
    | '/walks/$walkId/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  GalleryRoute: typeof GalleryRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  MoreRoute: typeof MoreRoute
  MyPawsRoute: typeof MyPawsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  PawreportTokenRoute: typeof PawreportTokenRoute
  PetsPetIdRoute: typeof PetsPetIdRoute
  PetsNewRoute: typeof PetsNewRoute
  VisitsVisitIdRoute: typeof VisitsVisitIdRoute
  WalksWalkIdRoute: typeof WalksWalkIdRouteWithChildren
  ClientsIndexRoute: typeof ClientsIndexRoute
  PetsIndexRoute: typeof PetsIndexRoute
  VisitsIndexRoute: typeof VisitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-paws': {
      id: '/my-paws'
      path: '/my-paws'
      fullPath: '/my-paws'
      preLoaderRoute: typeof MyPawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/pawreport/$token': {
      id: '/pawreport/$token'
      path: '/pawreport/$token'
      fullPath: '/pawreport/$token'
      preLoaderRoute: typeof PawreportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/': {
      id: '/pets/'
      path: '/pets'
      fullPath: '/pets/'
      preLoaderRoute: typeof PetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId': {
      id: '/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof PetsPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/new': {
      id: '/pets/new'
      path: '/pets/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof PetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits/': {
      id: '/visits/'
      path: '/visits'
      fullPath: '/visits/'
      preLoaderRoute: typeof VisitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits/$visitId': {
      id: '/visits/$visitId'
      path: '/visits/$visitId'
      fullPath: '/visits/$visitId'
      preLoaderRoute: typeof VisitsVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walks/$walkId': {
      id: '/walks/$walkId'
      path: '/walks/$walkId'
      fullPath: '/walks/$walkId'
      preLoaderRoute: typeof WalksWalkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walks/$walkId/report': {
      id: '/walks/$walkId/report'
      path: '/report'
      fullPath: '/walks/$walkId/report'
      preLoaderRoute: typeof WalksWalkIdReportRouteImport
      parentRoute: typeof WalksWalkIdRoute
    }
  }
}

interface InvoicesRouteChildren {
  InvoicesNewRoute: typeof InvoicesNewRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesNewRoute: InvoicesNewRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface WalksWalkIdRouteChildren {
  WalksWalkIdReportRoute: typeof WalksWalkIdReportRoute
}

const WalksWalkIdRouteChildren: WalksWalkIdRouteChildren = {
  WalksWalkIdReportRoute: WalksWalkIdReportRoute,
}

const WalksWalkIdRouteWithChildren = WalksWalkIdRoute._addFileChildren(
  WalksWalkIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  GalleryRoute: GalleryRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  MoreRoute: MoreRoute,
  MyPawsRoute: MyPawsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  PawreportTokenRoute: PawreportTokenRoute,
  PetsPetIdRoute: PetsPetIdRoute,
  PetsNewRoute: PetsNewRoute,
  VisitsVisitIdRoute: VisitsVisitIdRoute,
  WalksWalkIdRoute: WalksWalkIdRouteWithChildren,
  ClientsIndexRoute: ClientsIndexRoute,
  PetsIndexRoute: PetsIndexRoute,
  VisitsIndexRoute: VisitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
